# Site settings
title: PhoenixMatrix
description: > # this means to ignore newlines until "baseurl:"
  A world of JavaScript and opinionated discussions of every day software engineering problems
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://blog.phoenixmatrix.com" # the base hostname & protocol for your site
github_username:  phoenixmatrix

# Build settings
markdown: kramdown
highlighter: rouge
